[project]
name = "NeuralPLexer"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sibbe Bakker <sibbe.l.bakker@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python="*"
singularity = ">=3.8.6,<3.9"

[pypi-dependencies]
spython = "*"
